#!/bin/sh
#   intervals2bed.sh - convert samtools intervals into bed format
#
#   Author: Nowind
#   Created: 2013-07-26
#   Updated: 2013-07-26
#
#   Change logs:
#   Version 1.0.0 13/07/26: The initial version.

if [ -z $1 ]; then
    echo "usage: `basename $0` <*.intervals> [threshold]";
    exit 0;
fi

intervals_file=$1

if [ -z $2 ]; then
    grep "-" $intervals_file | sed 's/\-/\t/' | sed 's/\:/\t/' | \
        awk 'BEGIN{OFS="\t"} {print $1,($2-1),$3;}'
else
    grep "-" $intervals_file | sed 's/\-/\t/' | sed 's/\:/\t/' | \
        awk -v threshold=$2 'BEGIN{OFS="\t"} {len=$3-$2+1; if (len >= threshold) print $1,($2-1),$3;}'
fi
